"""rename department

Revision ID: a0a089e478dc
Revises: b682a4b19178
Create Date: 2024-07-05 08:30:53.810190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a089e478dc'
down_revision = 'b682a4b19178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('departments', 'department')
    # ### end Alembic commands ###
